// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearUnread(arg1) {
  return window['go']['main']['App']['ClearUnread'](arg1);
}

export function ConnectToPeer(arg1) {
  return window['go']['main']['App']['ConnectToPeer'](arg1);
}

export function CreateGroup(arg1, arg2) {
  return window['go']['main']['App']['CreateGroup'](arg1, arg2);
}

export function GetActiveTheme() {
  return window['go']['main']['App']['GetActiveTheme']();
}

export function GetGroups() {
  return window['go']['main']['App']['GetGroups']();
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetPeerStatus(arg1) {
  return window['go']['main']['App']['GetPeerStatus'](arg1);
}

export function GetPeers() {
  return window['go']['main']['App']['GetPeers']();
}

export function GetSelfInfo() {
  return window['go']['main']['App']['GetSelfInfo']();
}

export function GetUnread(arg1) {
  return window['go']['main']['App']['GetUnread'](arg1);
}

export function IsConnected(arg1) {
  return window['go']['main']['App']['IsConnected'](arg1);
}

export function IsReady() {
  return window['go']['main']['App']['IsReady']();
}

export function ListThemes() {
  return window['go']['main']['App']['ListThemes']();
}

export function NotifyFrontendReady() {
  return window['go']['main']['App']['NotifyFrontendReady']();
}

export function SearchGifs(arg1, arg2) {
  return window['go']['main']['App']['SearchGifs'](arg1, arg2);
}

export function SearchMessages(arg1) {
  return window['go']['main']['App']['SearchMessages'](arg1);
}

export function SendGroupMessage(arg1, arg2) {
  return window['go']['main']['App']['SendGroupMessage'](arg1, arg2);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SendReaction(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendReaction'](arg1, arg2, arg3);
}

export function SendReadReceipts(arg1) {
  return window['go']['main']['App']['SendReadReceipts'](arg1);
}

export function SendTyping(arg1, arg2) {
  return window['go']['main']['App']['SendTyping'](arg1, arg2);
}

export function SetStatus(arg1) {
  return window['go']['main']['App']['SetStatus'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function TrendingGifs(arg1) {
  return window['go']['main']['App']['TrendingGifs'](arg1);
}
