// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {chat} from '../models';
import {discovery} from '../models';
import {config} from '../models';
import {tenor} from '../models';

export function ClearUnread(arg1:string):Promise<void>;

export function ConnectToPeer(arg1:string):Promise<void>;

export function CreateGroup(arg1:string,arg2:Array<string>):Promise<chat.Group>;

export function GetActiveTheme():Promise<string>;

export function GetGroups():Promise<Array<chat.Group>>;

export function GetMessages(arg1:string):Promise<Array<chat.Message>>;

export function GetPeerStatus(arg1:string):Promise<string>;

export function GetPeers():Promise<Array<discovery.Peer>>;

export function GetSelfInfo():Promise<Record<string, string>>;

export function GetUnread(arg1:string):Promise<number>;

export function IsConnected(arg1:string):Promise<boolean>;

export function ListThemes():Promise<Array<config.ThemeInfo>>;

export function SearchGifs(arg1:string,arg2:number):Promise<Array<tenor.GIF>>;

export function SearchMessages(arg1:string):Promise<Record<string, Array<chat.Message>>>;

export function SendGroupMessage(arg1:string,arg2:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function SendReaction(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendReadReceipts(arg1:string):Promise<void>;

export function SendTyping(arg1:string,arg2:boolean):Promise<void>;

export function SetStatus(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function TrendingGifs(arg1:number):Promise<Array<tenor.GIF>>;
